### ISSUE TITLE
Problem with n_time_neighbors and intentional bottlenecks

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_opm#106]
In the chunking update, if a job has a prereq and n_time_neighbors is all, opm will only make 1 job, not 1 job per file.

For example, after smooth_cal I want to calculate redundant visibility solutions for every file using the output of smooth_cal. Only one smooth_cal job actually does anything, but it creates calfits files for all JDs. I need every smooth_cal job to finish before I continue on with any UPDATE_OMNI_SOL tasks. I then want one job per JD to use these calfits files to update the omnical visibility solutions. Right now it just creates a job for the first JD or the center JD depending on `time_centered`.

**Comment by adampbeardsley** [comment]
@plaplant and I are chatting about this, and realize your example may actually be easy to accommodate with the current code. Could you try this?
```
[UPDATE_OMNISOL]
prereqs = "CAL_SMOOTH"
args = ["{basename}"]
```

It looks weird because we're not using `n_time_neighbors`, but under the hood, it should see that `CAL_SMOOTH` only ran one job that "touched" all the observations. So a given obsid in the `UPDATE_OMNISOL` step will see that it needs that one job to be done before it can expect output for its obs.

If all works, it should launch a job for each obs, but none of them will run until the one smoothcal job is done.

**Comment by adampbeardsley** [comment]
Admittedly, this is not a complete solution... we're working on that.

**Comment by adampbeardsley** [comment]
Ok, more notes from our chat. We've come to realize we sorta overloaded the idea of `n_time_neighbors` as both referring to the previous step (the prereq) as well as the current step. But we agree it's better to think about it strictly as referring to the prereq. So I'm going to take a pass through the code to ensure that assumption holds.

But I think I'll also need to do some work to better interpret what `"all"` means for `n_time_neighbors`. Right now it's immediately interpreted as the length of the obsid list, say 100. But then when it tries to create a job for obsid #95, it sees it just doesn't have 100 neighbors, so it stops and doesn't run. What I'd like to do instead is say "all" refers to the full list, regardless of which obsid I'm launching right now.

With that change, I think this snippet should work:
```
[XRFI_DAY_THRESHOLD]
prereqs = "XRFI"
args = ["${XRFI_DAY_THRESHOLD_OPTS:nsig_f}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_f_adj}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t_adj}",
        "{obsid_list}"]
n_time_neighbors = "all"
stride_length = "all"
time_centered = false

[CAL_SMOOTH]
prereqs = "XRFI_DAY_THRESHOLD"
n_time_neighbors = "all"
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}", "${CAL_SMOOTH_OPTS:freq_scale}", "${CAL_SMOOTH_OPTS:time_scale}",
        "${CAL_SMOOTH_OPTS:tol}", "${CAL_SMOOTH_OPTS:filter_mode}", "${CAL_SMOOTH_OPTS:window}",
        "${CAL_SMOOTH_OPTS:maxiter}", "${CAL_SMOOTH_OPTS:alpha}", "${CAL_SMOOTH_OPTS:freq_threshold}",
        "${CAL_SMOOTH_OPTS:time_threshold}", "${CAL_SMOOTH_OPTS:ant_threshold}", "${CAL_SMOOTH_OPTS:lst_blacklists}"]

[UPDATE_OMNISOL]
prereqs = "CAL_SMOOTH"
n_time_neighbors = "all"
stride_length = 1
time_centered = false
args = ["{basename}"]
```

Note that in all these steps, we require the entire previous step to be finished. But the `stride_length` is what is handling which jobs actually run. If `stride_length=1`, it will step through each observation. But if `stride_length="all"`, it will start with the first one, but then step over all the remaining observations -- only running one job.

I think this will satisfy Josh's case, as well as the crazy corner turn stuff EDubbs is working on.

**Comment by jsdillon** [comment]
Thanks @plaplant and @adampbeardsley for fixing this in #107. I think we can close this issue.
