### ISSUE TITLE
Error in about XRFI in the makeflow Process

### ISSUE THREAD

**Issue by Zhilei** [HERA-Team/hera_opm#115]
After running the makeflow file (*.mf), an error file related to XRFI was generated:

_zen.2458937.29002.sum.uvh5.XRFI_DAY_THRESHOLD.log.error_

with the content as:

> Fri Sep  4 13:38:26 MDT 2020
> xrfi_day_threshold_run.py /users/zxu/lustre/2458937_demo/zen.2458937.29002.sum.uvh5 --skip_making_flagged_abs_calfits --nsig_f=7.0 --nsig_t=7.0 --nsig_f_adj=3.0 --nsig_t_adj=3.0 --clobber
> Traceback (most recent call last):
>   File "/users/zxu/anaconda3/envs/hera/bin/xrfi_day_threshold_run.py", line 16, in <module>
>     nsig_f_adj=args.nsig_f_adj, nsig_t_adj=args.nsig_t_adj, clobber=args.clobber)
>   File "/users/zxu/anaconda3/envs/hera/lib/python3.7/site-packages/hera_qm/xrfi.py", line 2434, in day_threshold_run
>     uvf_total = filled_metrics_that_exist[0].copy()
> IndexError: list index out of range
> Fri Sep  4 13:38:28 MDT 2020

It is not very clear to me what caused that so I was wondering whether I can get some help on this. Thanks!

**Comment by jsdillon** [comment]
Try downloading the newest makeflow TOML. I think thi error has been fixed already.

**Comment by Zhilei** [comment]
Thanks for the suggestion!
I pulled the hera_opm and hera_pipeline repos and updated my NRAO .toml file as well, it terms out only one line was added which is `prereq_chunk_size = "all"`. 

I then reran everything again but the error is still here. It is possible I am doing something wrong, please feel free to let me know.

**Comment by Zhilei** [comment]
Thanks for the suggestions!

I reran the script again with around 30 files (instead of one).  I did not see any error files, but none of the xrfi folders were produced either. So probably that step was not executed.

A funny thing I noticed was that I saw this warning message at the end of the output after the `build_makeflow_from_config ...` command
> UserWarning: Collecting stragglers is incompatible with gaps between consecutive strides. Not collecting stragglers...
I suppose it may be useful to debug.

**Comment by jsdillon** [comment]
You probably need more than 30 files, since the chunk size is 31 (or lower the chunk size). This again might be the same issue as before with the straggler issue.

**Comment by Zhilei** [comment]
After installing SSNIS and updated xrfi, I collected 34 data files and ran the makeflow again.
The only error file I got was `zen.2458937.29002.sum.uvh5.XRFI_DAY_THRESHOLD.log.error` with the content as:

> Sun Sep  6 20:44:06 MDT 2020
> xrfi_day_threshold_run.py /users/zxu/lustre/2458937_demo/zen.2458937.29002.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29024.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29046.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29069.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29091.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29114.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29136.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29158.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29181.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29203.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29225.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29248.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29270.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29292.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29315.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29382.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29404.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29427.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29449.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29471.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29494.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29516.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29539.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29561.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29583.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29606.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29628.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29650.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29762.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29785.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29852.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29874.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29896.sum.uvh5 /users/zxu/lustre/2458937_demo/zen.2458937.29919.sum.uvh5 --skip_making_flagged_abs_calfits --nsig_f=7.0 --nsig_t=7.0 --nsig_f_adj=3.0 --nsig_t_adj=3.0 --clobber
> Warning: 'partition' will ignore the 'mask' of the MaskedArray.
> Warning: converting a masked element to nan.
> invalid value encountered in greater_equal
> File /users/zxu/lustre/2458937_demo/zen.2458937.cross_threshold_flags.h5 exists; clobbering
> File /users/zxu/lustre/2458937_demo/zen.2458937.auto_threshold_flags.h5 exists; clobbering
> File /users/zxu/lustre/2458937_demo/zen.2458937.combined_threshold_flags.h5 exists; clobbering
> File /users/zxu/lustre/2458937_demo/zen.2458937.total_threshold_flags.h5 exists; clobbering
> rm -f /users/zxu/lustre/2458937_demo/zen.2458937.29002.stage_1_xrfi
> rm: cannot remove ‘/users/zxu/lustre/2458937_demo/zen.2458937.29002.stage_1_xrfi’: Is a directory
> Sun Sep  6 20:44:12 MDT 2020

Another thing I noticed is that in the `screen` session I am running the makeflow command, something seems to never stop running since the prompt never appeared until I kill the job. However, I did not see any job from me running on the `qstat` list. Maybe these two issues are related meaning the script is stuck somewhere?
