### ISSUE TITLE
Update run_firstcal to take in {JD}.HH.uv.ant_metrics.json

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_opm#15]
Using bad ants basically already accomplishes this, but since we have the ant_metrics already, we might as well use them too and make sure commissioning didn't miss any antennas that should have been flagged when they gave us the synthesized antenna flags.

**Comment by jsdillon** [comment]
Also, that's what's on the omnigraffle: https://www.dropbox.com/s/b0rbxs6u4wo2cio/H1C%20IDR2.1%20Workflow.pdf?dl=0

**Comment by plaplant** [comment]
Do we want to pass these in to omnical too? That's what we do in RTP.

**Comment by jsdillon** [comment]
Yes, let's.

**Comment by plaplant** [comment]
This was addressed in b83c2497323aab2e255ab5147598b8d020d5e049.
