### ISSUE TITLE
Implement a 24 hour cutoff on individual pipeline processes

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_opm#19]
Ideally, it would raise some sort of error (not produce a .out) and still spit out its final time at the end of the log.

**Comment by plaplant** [comment]
This was added in 2c4405d2f8073e9297da7abc135ca042bc744f76. Note that this will not produce a .out file, but the time will _not_ be printed at the end of the job. (Once the time limit of 24 hours is reached, the job abruptly terminates.) Modifying the task scripts to print the final time would require a more significant modification (and might rely on tools that are not available everywhere, limiting portability), so it might be simpler to modify the script assessing task completion status.

**Comment by jsdillon** [comment]
That's fine. Does the log reflect the termination? For example, the jupyter job outputs `PBS: job killed: walltime 86417 exceeded limit 86400`. Is that sort of universal? Can I search for "PBS: job killed: walltime"?

**Comment by plaplant** [comment]
My guess is not... The PBS output just disappears into the ether. However, I came up with a workaround where the `heramgr` email account will be notified if the job times out. Is that an acceptable failure mode?

**Comment by jsdillon** [comment]
I'll figure something out.

**Comment by jsdillon** [comment]
Ok, now I just need to add a fourth category to my pipeline_status.py called "timed out."

**Comment by plaplant** [comment]
This was fixed in PR #20.
