### ISSUE TITLE
Bump up skip_wgts in config to .5

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_opm#27]

**Comment by jsdillon** [comment]
Also the defaults in hera_cal.

**Comment by jsdillon** [comment]
skip_wgt is there just to save computational time, as far as I know. @zakiali might have something to add. Lots of flags makes the delay clean slow, but it doesn't necessarily make it give bad answers.

I'd rather throw more compute at the problem and let xrfi decide when to declare entire integration bad, rather than the delay filtering algorithm.

**Comment by adampbeardsley** [comment]
Hmm, that's fair. I went ahead and approved the hera_cal PR, but let's wait and see if Zaki wants to weigh in before merging.

**Comment by zakiali** [comment]
From what I know, it’s about saving computation time. I’d say go ahead and merge. It’s still a keyword so the user can change it if they want to use highly flagged integrations.
