### ISSUE TITLE
change config syntax to JSON

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_opm#33]
I think the config file parsing would become more easier, clearer and more flexible if we conformed to JSON syntax within the header blocks of a config file, and then used `json.loads` to convert each header item into a python data type, rather than using the stripped string output of `config.get`. @plaplant let me know what you think. If you agree, then perhaps we wait on this until after the IDR2 release.

**Comment by plaplant** [comment]
I've looked into this a little bit, and we may be able to accomplish this by using a proper TOML parsing package (like this one: https://github.com/uiri/toml) instead of the built-in `ConfigParser`. I'll see if I can get this up and running in the near future.
